# Operating Systems Project - myshell Makefile
# 目标: 依赖项
# 	构建命令 (注意前面必须是 Tab 键)

# 默认目标
myshell: myshell.c utility.c myshell.h
	gcc -Wall myshell.c utility.c -o myshell

# 清理生成的文件
clean:
	rm -f myshell *.o